package:
  name: blaze
  version: "0.7.0"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
  build:
    - python
    - numpy
    - multipledispatch
    - sqlalchemy
    - pandas
    - h5py
    - datashape
    - into
    - flask
    - requests
    - cytoolz
    - toolz
    - bcolz
    - pytables
    - psutil
    - into
    - pymongo
    - pytest
    - unittest2 [py26]

  run:
    - python
    - numpy
    - multipledispatch
    - sqlalchemy
    - pandas
    - h5py
    - datashape
    - into
    - flask
    - requests
    - cytoolz
    - toolz
    - bcolz
    - pytables
    - psutil
    - into
    - pymongo
    - unittest2 [py26]

test:
  requires:
    - pytest
    - coverage

  commands:
    - python -c "import blaze; blaze.test()"

about:
  home: http://blaze.pydata.org
  license: BSD
